### ISSUE TITLE
NER Testing

### ISSUE THREAD

**Issue by L30N1DAS** [kastle-lab/kg-chatbot#13]
I looked at how NER in some popular Python libraries for NLP would work for my project since it heavily entails video game data. I have used some sample general tests and some tests more specific to video game data. In some cases, my tests were not fully random but actually framed in such a way to to obtain a certain entity tag. The tests can be seen below:

## General

1. Bill Gates founded Microsoft Corp. together with Paul Allen in 1975.

NLTK
```
(S
  (PERSON Bill/NNP)
  (PERSON Gates/NNP)
  founded/VBD
  (ORGANIZATION Microsoft/NNP)
  Corp./NNP
  together/RB
  with/IN
  (PERSON Paul/NNP Allen/NNP)
  in/IN
  1975/CD
  ./.)
```
Spacy
```
[('Bill Gates', 'PERSON'),
 ('Microsoft Corp.', 'ORG'),
 ('Paul Allen', 'PERSON'),
 ('1975', 'DATE')]
```

2. European authorities fined Google a record $5.1 billion on Wednesday for abusing its power in the mobile phone market and ordered the company to alter its practices.

NLTK
```
(S
  (GPE European/JJ)
  authorities/NNS
  fined/VBD
  (PERSON Google/NNP)
  a/DT
  record/NN
  $/$
  5.1/CD
  billion/CD
  on/IN
  Wednesday/NNP
  for/IN
  abusing/VBG
  its/PRP$
  power/NN
  in/IN
  the/DT
  mobile/JJ
  phone/NN
  market/NN
  and/CC
  ordered/VBD
  the/DT
  company/NN
  to/TO
  alter/VB
  its/PRP$
  practices/NNS
  ./.)
```
Spacy
```
[('European', 'NORP'),
 ('Google', 'ORG'),
 ('$5.1 billion', 'MONEY'),
 ('Wednesday', 'DATE')]
```

3. Jane Austen wrote Pride and Prejudice.

NLTK
```
(S
  (PERSON Jane/NNP)
  (PERSON Austen/NNP)
  wrote/VBD
  (PERSON Pride/NNP)
  and/CC
  Prejudice/NNP
  ./.)
```
Spacy
```
[('Jane Austen', 'PERSON'),
 ('Pride and Prejudice', 'WORK_OF_ART')]
```

4. Mount Everest is the tallest mountain in the world.

NLTK
```
(S
  (PERSON Mount/NNP)
  (ORGANIZATION Everest/NNP)
  is/VBZ
  the/DT
  tallest/JJS
  mountain/NN
  in/IN
  the/DT
  world/NN
  ./.)
```
Spacy
```
[('Mount Everest', 'LOC')]
```

## Video Game

1. Gearbox Software developed Borderlands and released it in 2009. It sold 600,000 units in Europe.

NLTK
```
(S
  (PERSON Gearbox/NNP)
  (PERSON Software/NNP)
  developed/VBD
  (PERSON Borderlands/NNP)
  and/CC
  released/VBD
  it/PRP
  in/IN
  2009/CD
  ./.
  It/PRP
  sold/VBD
  600,000/CD
  units/NNS
  in/IN
  (GPE Europe/NNP)
  ./.)
```
Spacy
```
[('Gearbox Software', 'PERSON'),
 ('Borderlands', 'ORG'),
 ('2009', 'DATE'),
 ('600,000', 'CARDINAL'),
 ('Europe', 'LOC')]
```

2. In The Legend of Zelda: Skyward Sword, Ghirahim seeks to revive the Demon King, Demise.

NLTK
```
(S
  In/IN
  The/DT
  (ORGANIZATION Legend/NNP)
  of/IN
  (GPE Zelda/NNP)
  :/:
  (PERSON Skyward/NNP Sword/NNP)
  ,/,
  (PERSON Ghirahim/NNP)
  seeks/VBZ
  to/TO
  revive/VB
  the/DT
  (ORGANIZATION Demon/NNP)
  King/NNP
  Demise/NNP
  ./.)
```
Spacy
```
[('The Legend of Zelda:', 'WORK_OF_ART'),
 ('Skyward Sword', 'PERSON'),
 ('Ghirahim', 'PERSON'),
 ('Demise', 'PERSON')]
```

3. Sonic the Hedgehog is said to be as fast as the speed of sound, approximately 343 meters per second.

NLTK
```
(S
  Sonic/NNP
  the/DT
  (ORGANIZATION Hedgehog/NNP)
  is/VBZ
  said/VBD
  to/TO
  be/VB
  as/RB
  fast/RB
  as/IN
  the/DT
  speed/NN
  of/IN
  sound/NN
  ,/,
  approximately/RB
  343/CD
  meters/NNS
  per/IN
  second/NN
  ./.)
```
Spacy
```
[('Hedgehog', 'PERSON'),
 ('approximately 343 meters', 'QUANTITY')]
```

4. Metal Gear Solid takes place in an alternate history in which the Cold War continued into the 1990s, ending at some point near the end of the 20th century.

NLTK
```
(S
  (ORGANIZATION Metal/JJ)
  (ORGANIZATION Gear/NNP Solid/NNP)
  takes/VBZ
  place/NN
  in/IN
  an/DT
  alternate/JJ
  history/NN
  in/IN
  which/WDT
  the/DT
  Cold/NNP
  War/NNP
  continued/VBD
  into/IN
  the/DT
  1990s/CD
  ,/,
  ending/VBG
  at/IN
  some/DT
  point/NN
  near/IN
  the/DT
  end/NN
  of/IN
  the/DT
  20th/JJ
  century/NN
  ./.)
```
Spacy
```
[('the Cold War', 'EVENT'),
 ('the 1990s', 'DATE'),
 ('the end of the 20th century', 'DATE')]
```

5. In The Legend of Zelda: Breath of the Wild, Link meets King Rhoam Bosphoramus Hyrule after awaking from a century of slumber in the Shrine of Resurrection.

NLTK
```
(S
  In/IN
  The/DT
  (ORGANIZATION Legend/NNP)
  of/IN
  (GPE Zelda/NNP)
  :/:
  Breath/NN
  of/IN
  the/DT
  (ORGANIZATION Wild/NNP)
  ,/,
  (PERSON Link/NNP)
  meets/VBZ
  King/NNP
  (PERSON Rhoam/NNP Bosphoramus/NNP Hyrule/NNP)
  after/IN
  awaking/VBG
  from/IN
  a/DT
  century/NN
  of/IN
  slumber/NN
  in/IN
  the/DT
  (ORGANIZATION Shrine/NNP)
  of/IN
  Resurrection/NNP
  ./.)
```
Spacy
```
[('The Legend of Zelda: Breath of the Wild', 'WORK_OF_ART'),
 ('Hyrule', 'PERSON'),
 ('a century', 'DATE'),
 ('the Shrine of Resurrection', 'WORK_OF_ART')]
```

Some notes:
- The NLTK results have NER and POS. I'm not sure if this is necessary, but I looked at multiple tutorials, and all of them performed NER _after_ POS.
- My testing code can be viewed in the `NLP` branch at `resources/scripts/NLP`. My sources can viewed at the bottom of those files.
- Overall, both NLTK and Spacy had issues with NER relative to my project. NLTK, especially, had trouble identifying entities even for general cases (perhaps I was doing it in a less than ideal way because the results were surprisingly disappointing). Spacy, on the hand, had issues; but they were not as severe as the ones experienced by NLTK. Spacy identified more kinds of entities and was even capable of identifying some more well-known video games as `WORK_OF_ART`. As such, Spacy's NER with some customization may be the ideal route(?).

**Comment by cogan-shimizu** [comment]
Ok, so in light of these findings, it seems that we want to move forward using Spacy's model. The question now is how exactly we move forward. Can we fine tune the model, provide additional training data? Would we want to build an index of game titles and every time we have a person/org run it through to be filtering? I'd guess this is a pretty "dumb" approach (i.e., not really semantically driven) and would probably fail at edge cases like "Zelda is a person AND a game".

**Comment by cogan-shimizu** [comment]
The question you should probably thinking about now is how exactly do we improve performance of the NER model.
