### ISSUE TITLE
Make Voice Actor Dataset

### ISSUE THREAD

**Issue by L30N1DAS** [kastle-lab/kg-chatbot#2]
Make Voice Actor Dataset using [behindthevoiceactors.com](https://www.behindthevoiceactors.com/video-games).
![image](https://user-images.githubusercontent.com/77419369/223532129-5b19b8ae-b200-4bc5-93e6-959537341e9b.png)

**Comment by L30N1DAS** [comment]
I believe this script is complete. I still need to generate the dataset and determine if there are errors, however. In addition, I may go back to include games under the `#` category depending on whether time allows.

**Comment by L30N1DAS** [comment]
No progress. Look at corresponding branch for code and dataset

**Comment by cogan-shimizu** [comment]
upload then close this issue.
