### ISSUE TITLE
Make Illustrator Dataset

### ISSUE THREAD

**Issue by L30N1DAS** [kastle-lab/kg-chatbot#3]
Make Illustrator dataset (either find one or scrape a database)

**Comment by L30N1DAS** [comment]
Using this database: https://www.creativeuncut.com/game-art-galleries.html. This script is complete, and the dataset has been generated with game name and game artists. Some games have `???` as the artist, and I intend to remove those entries.

**Comment by L30N1DAS** [comment]
No progress. Look at corresponding branch for code and dataset

**Comment by cogan-shimizu** [comment]
Code quality needs to be improved. update inthread, close issue when complete.
