### ISSUE TITLE
Make Music Dataset

### ISSUE THREAD

**Issue by L30N1DAS** [kastle-lab/kg-chatbot#6]
Make a Music Dataset that includes: Album name, a list of tracks in that album, a list of games that album's music is from, and composer. The database I'm using is: https://vgmdb.net/search?do=results&id=1061698&field=&. This links also show the fields I am sorting by.

**Comment by L30N1DAS** [comment]
Making progress with this. Was able to extract album name and tracks. Haven't made as much progress with the composer and games aspects due to inconsistencies in the html for that data.

**Comment by L30N1DAS** [comment]
Was able to get composer done. Working on games' English names (struggling somewhat, but I'll figure it out). Look at corresponding branch to see code

**Comment by cogan-shimizu** [comment]
needs to be re-run. Script completes successfully, however. Update inthread.
